config/routes.rb
Rails.application.routes.draw do
  resources :tasks, except: [:new, :show]

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task = Task.new
    @tasks = Task.all
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_url
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_url
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_url
  end

  def task_params
    params.require(:task).permit(:name, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTasks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>
<%= form_for(@task) do |f| %>
  <p>
    名前:<%= f.text_field :name %>
    内容:<%= f.text_field :body %>
    <%= f.submit %>
  </p>
<% end %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<% if @tasks.present? %>
  <ul>
    <% @tasks.each do |task| %>
    <li>
      <%= task.name %>  |  <%= task.body %> | <%= link_to "編集", edit_task_path(task) %> | <%= link_to "削除", task_path(task), method: :delete, data: { confirm: '本当に削除しますか？'} %>
    </li>
    <% end %>
  </ul>
<% else %>
<p>タスクがありません</p>
<% end %>

<%= form_for(@task) do |f| %>
  <p>
    名前:<%= f.text_field :name %>
    内容:<%= f.text_field :body %>
    <%= f.submit %>
  </p>
<% end %>